### ISSUE TITLE
Latest subfinder version requires go 1.24.3 and causes a conflict on windows cause it relies on zcrypto

### ISSUE THREAD

**Issue by DEMON1A** [projectdiscovery/subfinder#1589]
While attempting to use subfinder APIs in my code using the latest version I get this errors switching to another version

```batch
E:\demonia\isnt\me>go1.21.0 mod tidy
go: github.com/projectdiscovery/subfinder/v2@v2.7.1 requires go >= 1.24.0; switching to go1.24.3
```

Yet subfinder relies on `zcrypto` which is using a lower go version causing it to fail

```batch
E:\who\is\demonia>go1.21.0 run ihatemylife.go
# github.com/zmap/zcrypto/ct/x509
C:\Users\demonia\go\pkg\mod\github.com\zmap\zcrypto@v0.0.0-20250418211859-7510c141e4b7\ct\x509\root_windows.go:112:20: cannot use uintptr(unsafe.Pointer(sslPara)) (value of type uintptr) as syscall.Pointer value in struct literal
# github.com/zmap/zcrypto/x509
C:\Users\demonia\go\pkg\mod\github.com\zmap\zcrypto@v0.0.0-20250418211859-7510c141e4b7\x509\root.go:27:32: undefined: loadSystemRoots
```

Zcrypto relies on go core functions that was replaced later and another implementations were put to replace those functions, So making it work with the required go version *go1.24.3* is impossible, it's either you lower your go version requirements to follow your documentation saying `go1.21.0` is the version to go, or you can create a zcrypto fork, maintain it and adjust it to use the new golang core functionality

**Comment by dogancanbakir** [comment]
@DEMON1A Thanks for letting us know. Updated the required go version in the doc.
